permission:
  - name: log
    path: /query
    api:
      - name: 获取日志列表
        method: GET
        path: /api/query/logs
      - name: 获取日志图表
        method: GET
        path: /api/query/charts
      - name: 获取日志tables
        method: GET
        path: /api/query/tables
  - name: alarm
    path: /alarm
    children:
      - name: rules
        path: /alarm/rules
      - name: notifications
        path: /alarm/notifications
  - name: configure
    path: /configure
  - name: systemSettings
    path: /sys
    children:
      - path: /sys/instances
        name: database
        api:
        - name: 查询数据库连接
          method: GET
          path: /api/sys/instances
        - name: 新增数据库连接
          method: POST
          path: /api/sys/instances
        - name: 更新数据库连接
          method: PATCH
          path: /api/sys/instances/:id
        - name: 删除数据库连接
          method: DELETE
          path: /api/sys/instances/:id
      - path: /sys/clusters
        name: cluster
        api:
        - name: 查询数据库连接
          method: GET
          path: /api/v1/sys/clusters
        - name: 新增数据库连接
          method: POST
          path: /api/v1/sys/clusters
        - name: 更新数据库连接
          method: PATCH
          path: /api/v1/sys/clusters/:id
        - name: 删除数据库连接
          method: DELETE
          path: /api/v1/sys/clusters/:id
