name: golangci-lint
on:
  push:
    tags:
      - v*
    branches:
      - master
      - 'fix/ci'
  pull_request:
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60
          args: --timeout=10m --print-issued-lines=true --print-linter-name=true --uniq-by-line=true

