name: golangci-lint
on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
      - 'feature/docker-ci'

  pull_request:
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.54

          # Optional: working directory, useful for monorepos
          #          working-directory: ./

          # Optional: golangci-lint command line arguments.
          args: --timeout=10m --print-issued-lines=true --print-linter-name=true --uniq-by-line=true

          # Optional: show only new issues if it's a pull request. The default value is `false`.
          only-new-issues: true

          # Optional: if set to true then the action will use pre-installed Go
          # skip-go-installation: true
