name: publish-release

on:
  push:
    tags:
      - "v**"
    branches:
      - 'fix/ci'
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.yarn
          key: yarn-${{ hashFiles('ui/yarn.lock') }}
          restore-keys: yarn-
      - name: yarn build dist
        run: |
          cd ui
          yarn install --frozen-lockfile
          yarn run build
          rm -rf ../api/internal/ui/dist
          cp -rf dist ../api/internal/ui
      - name: Set up Go
        uses: actions/setup-go@v5
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          # 'latest', 'nightly', or a semver
          version: '~> v2'
          args: release --clean --skip=validate
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}